keycloak: 
  auth:
    ## @param auth.adminUser Keycloak administrator user
    ##
    adminUser: admin
    ## @param auth.adminPassword Keycloak administrator password for the new user
    ##
    adminPassword: "admin"

  service:
    ## @param service.type Kubernetes service type
    ##
    type: LoadBalancer

  postgresql:
    enabled: true
    auth:
      postgresPassword: ""
      username: bn_keycloak
      password: "password"
      database: bitnami_keycloak
      existingSecret: ""
      secretKeys:
        userPasswordKey: password
    architecture: standalone

  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.import=/config/test-realm.json"      
  extraVolumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
  extraVolumes:
    - name: config
      configMap:
        name: keycloak-realm
        items:
        - key: "test-realm.json"
          path: "test-realm.json"