# Default values for account.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
base-ms-chart:

  nameOverride: "account-service"
  fullnameOverride: "account-service"

  image:
    repository: canpolatoral/receiver-service
    pullPolicy: IfNotPresent
    tag: "1.0.13"

  readinessProbe:
    httpGet:
      path: /health
      port: http

  livenessProbe:
    httpGet:
      path: /health
      port: http

  peerAuthentication:
    enabled: true
    
    mtls:
      mode: STRICT

  requestAuthentication:
    enabled: true

    # jwtRules:
    #   - issuer: http://keycloak.keycloak.svc/realms/test
    #     jwksUri: http://keycloak.keycloak.svc/realms/test/protocol/openid-connect/certs

    jwtRules:
      - issuer: http://keycloak.keycloak.svc/realms/test
        jwks: > 
          {"keys": [{"kid": "SlvCS4TPpSgjdowzQhAx4crHwp45fTePz6fMXKlw9wU", "kty": "RSA", "alg": "RS256", "use": "sig", "n": "yCMejU9NT6Dc9OxgbQSR6m-sw3QNpvbfpHsnESLhwKc1pWrWZcCdXJ0jSu7Fee435ZV5GhtGFHugBaqPoKy8Pa_8be6aIXLlq7ujo-tbxw4IqeV9LJ5HLyR6lv7R0PuV6CzV02uThJWExwz543BRHXMjzA1uyjbeYcaldte68ZtivX7PLPzwZl6DFdjbG9FE8GpsGkTaboVXQQqSd_Azc93P_vDGkvj2cPfiUDFphGwljgqRH09cqaWTqocu8jfEXgP7i-i7N3rg3iTVrf21niEtWUjApXu3J8MeTnsFwYy4aH8pGxix7B5_3NPVdFBaRn9vcKISwBatoVgvHJ0FqQ", "e": "AQAB", "x5c": ["MIIClzCCAX8CBgGVWu9DyTANBgkqhkiG9w0BAQsFADAPMQ0wCwYDVQQDDAR0ZXN0MB4XDTI1MDMwMzA3MzQ0NFoXDTM1MDMwMzA3MzYyNFowDzENMAsGA1UEAwwEdGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMgjHo1PTU+g3PTsYG0EkepvrMN0Dab236R7JxEi4cCnNaVq1mXAnVydI0ruxXnuN+WVeRobRhR7oAWqj6CsvD2v/G3umiFy5au7o6PrW8cOCKnlfSyeRy8kepb+0dD7legs1dNrk4SVhMcM+eNwUR1zI8wNbso23mHGpXbXuvGbYr1+zyz88GZegxXY2xvRRPBqbBpE2m6FV0EKknfwM3Pdz/7wxpL49nD34lAxaYRsJY4KkR9PXKmlk6qHLvI3xF4D+4vouzd64N4k1a39tZ4hLVlIwKV7tyfDHk57BcGMuGh/KRsYsewef9zT1XRQWkZ/b3CiEsAWraFYLxydBakCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAJwwFGezpxTDJUnkW4llzRi7QLAtGsG6XrPmQEWg1JaHIQuQNVYdRX342YBXDxFN7FSDg832YSRi/LBni1Qok2ma8MDbnO4hcFpT+i+rjTJyxWpMAXLfxBwxcC6seBm2wqxOpRQXpc0k47BfBKsgi05fVKpvZ98kgvSL5tXCykPesPDfmnHBShvrH6XcmWdLiugW5Li+Wicl3WAJFu1uAsKfbWVSJ1WRl8oWbLwEktZAKXgPi3yHLEDbf6qtRcnRS3WGB3HDbJb2MHj6NashF/17fdHrrgSEHV2G9iPuKQFau621ArVa5i2a9hAThm0dJdSXi7odjUsTdERd6xCrn/Q=="], "x5t": "b2K6MPztU2wa-8McY1eRkG5f4es", "x5t#S256": "qXRLusdC5gRZDV0Dd1W07gl25ju5RWI07jJ9BYXnD7c"}, {"kid": "WkAil2-2yjkaJNyySAWP1HoU5fCvaQPNKzsmOnwQ7_M", "kty": "RSA", "alg": "RSA-OAEP", "use": "enc", "n": "rSpUJyMqSRtbLEXAa5Mqd6KZwbjJ_4nG4L5BZ7NfRR8_2FxxpcN7WLhhYl42qs69lfxgM8-k_TFY1kBo2ayOPOsK3w7398OVwiRDZH_Xh0yOKvzUw0QQSS2PtE05-PWT-VPc7QVKVPnZavsLaWqZBDxbSVUJ0ZuWH52AaB4445QDChmwxIYYc0cAv3NNSa-DcGxKiqwk2ox8vWDwAiJyLNus7Ml25lXwA2peZXghI8bo-jxEdL8bU7nT-1D4eSNNtaWomoRT8cXtEzasY_c7x78YFYlMAAxqrF8gOw05TXmPxp4pW4b0zDHIOG6smRG5SIp6q-Sbz-prlcWiMG8SBw", "e": "AQAB", "x5c": ["MIIClzCCAX8CBgGVWu9C9zANBgkqhkiG9w0BAQsFADAPMQ0wCwYDVQQDDAR0ZXN0MB4XDTI1MDMwMzA3MzQ0NFoXDTM1MDMwMzA3MzYyNFowDzENMAsGA1UEAwwEdGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK0qVCcjKkkbWyxFwGuTKneimcG4yf+JxuC+QWezX0UfP9hccaXDe1i4YWJeNqrOvZX8YDPPpP0xWNZAaNmsjjzrCt8O9/fDlcIkQ2R/14dMjir81MNEEEktj7RNOfj1k/lT3O0FSlT52Wr7C2lqmQQ8W0lVCdGblh+dgGgeOOOUAwoZsMSGGHNHAL9zTUmvg3BsSoqsJNqMfL1g8AIicizbrOzJduZV8ANqXmV4ISPG6Po8RHS/G1O50/tQ+HkjTbWlqJqEU/HF7RM2rGP3O8e/GBWJTAAMaqxfIDsNOU15j8aeKVuG9MwxyDhurJkRuUiKeqvkm8/qa5XFojBvEgcCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAANRfkVxTOdDuWEbCeqFmEVuDY0IMrtfTFEiDtt8OngVbYtGYJEo8d7XLw+xIs0zXqalOrYae1YKw4ZtlngN5PSUjagYrYZjfBnHaS6oQz2N4AkZlRaWe6Htp4xUbRyfJ71L76OTNX/D8F+oeirvsls+8QWSa9qSgC6+qeNRofDJa+UEETIuISXJm/Rybgl+cJQKdJUJot+IouoNXHCT4bsuhFpjCSnXFf/RAMK2jyXNrAkWR39lqbh5noJVehDHs3ac7r7fOkDupTM6p9ZotOh+lAZgO3oVq+VCXmnXE3ZvN/7w/TImtI1k1sMHUedrip5aNgu0GbJ+BBjwdBQFkoQ=="], "x5t": "sniVAZBepjOqQQietB-AtFDCwe0", "x5t#S256": "uaogTqdPuFNizfyhe2SOqLVioQ6zj9vmvx3P95f_5ts"}]}


  authorizationPolicy:
    enabled: true

    allowedServiceAccounts:
      - namespace: transfer
        serviceAccount: transfer-service
      - namespace: istio-system
        serviceAccount: istio-ingressgateway
      # - namespace: customer
      #   serviceAccount: customer-service\

    allowedClients:
      - issuer: http://keycloak.keycloak.svc/realms/test
        #clientId: test-client-id
        clientId: 291e5a43-c687-49a0-b110-69381249c16f

  # resources:
  #   requests:
  #     cpu: "0m"
  #     memory: "0Mi"
  #   limits:
  #     cpu: "500m"
  #     memory: "256Mi"
