base-ms-chart:

  env:
    - name: PORT
      value: "80"
    - name: VERSION
      value: "MEYDAN"
    - name: SERVICE_NAME
      value: "Account Service"
    - name: ERROR_ENABLED
      value: "true"
    - name: ERROR_CODE
      value: "500"
    - name: ERROR_MESSAGE
      value: "Test error generated for LocalityLB"

  destinationRule:
    enabled: true

    trafficPolicy:
      connectionPool:
        http:
          maxRequestsPerConnection: 1

      loadBalancer:
        simple: ROUND_ROBIN
        localityLbSetting:
          enabled: true
          failover:
            - from: myd
              to: auh

      outlierDetection:
        consecutive5xxErrors: 1
        interval: "10s"
        baseEjectionTime: "1m"