# Default values for account.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
base-ms-chart:

  nameOverride: "account-service"
  fullnameOverride: "account-service"

  image:
    repository: canpolatoral/receiver-service
    pullPolicy: IfNotPresent
    tag: "1.0.0"

  mtls:
    mode: STRICT

  authorizationPolicy:
    enabled: true

    allowedSources:
      - namespace: transfer
        serviceAccount: transfer-service
      - namespace: istio-system
        serviceAccount: istio-ingressgateway
      # - namespace: customer
      #   serviceAccount: customer-service

  virtualService:
    enabled: true

    hosts:
      - "multicluster.mydemo.com"
    gateways:
      - "istio-system/ingress-gateway"
    http:
      match:
        prefix: "/account"
      rewrite:
        uri: "/test"
      route:
        destination:
          host: "account-service.account.svc.cluster.local"
          port:
            number: 80

  # resources:
  #   requests:
  #     cpu: "0m"
  #     memory: "0Mi"
  #   limits:
  #     cpu: "500m"
  #     memory: "256Mi"
