base-ms-chart:

  env:
    - name: PORT
      value: "80"
    - name: VERSION
      value: "ABU DHABI"
    - name: SERVICE_NAME
      value: "Account Service"

  destinationRule:
    enabled: false

    trafficPolicy:
      connectionPool:
        http:
          maxRequestsPerConnection: 1

      loadBalancer:
        simple: ROUND_ROBIN
        localityLbSetting:
          enabled: true
          failover:
            - from: auh
              to: zone1

      outlierDetection:
        consecutive5xxErrors: 1
        interval: "1s"
        baseEjectionTime: "1m"

  virtualService:
    enabled: true

    hosts:
      - "cluster2.multicluster.com"
    gateways:
      - "istio-system/ingress-gateway"
    http:
      match:
        prefix: "/account"
      rewrite:
        uri: "/test"
      route:
        destination:
          host: "account-service.account.svc.cluster.local"
          port:
            number: 80