# Default values for account.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
base-ms-chart:

  nameOverride: "account-service"
  fullnameOverride: "account-service"

  image:
    repository: canpolatoral/receiver-service
    pullPolicy: IfNotPresent
    tag: "1.0.13"

  readinessProbe:
    httpGet:
      path: /health
      port: http

  livenessProbe:
    httpGet:
      path: /health
      port: http

  peerAuthentication:
    enabled: true
    
    mtls:
      mode: STRICT

  requestAuthentication:
    enabled: true

    jwtRules:
      - issuer: http://keycloak.keycloak.svc/realms/test
        jwksUri: http://keycloak.keycloak.svc/realms/test/protocol/openid-connect/certs

  authorizationPolicy:
    enabled: true

    allowedServiceAccounts:
      - namespace: transfer
        serviceAccount: transfer-service
      - namespace: istio-system
        serviceAccount: istio-ingressgateway
      # - namespace: customer
      #   serviceAccount: customer-service\

    # allowedClients:
    #   - issuer: http://keycloak.keycloak.svc/realms/test
    #     clientId: 291e5a43-c687-49a0-b110-69381249c16f
        #clientId: test-client-id

  # resources:
  #   requests:
  #     cpu: "0m"
  #     memory: "0Mi"
  #   limits:
  #     cpu: "500m"
  #     memory: "256Mi"
