gateways:
  - name: cross-network-gateway
    apiVersion: networking.istio.io/v1alpha3
    selector:
      istio: eastwestgateway
    servers:
      - port:
          number: 15443
          name: tls
          protocol: TLS
        tls:
          mode: AUTO_PASSTHROUGH
        hosts:
          - "*.local"

  - name: ingress-gateway
    apiVersion: networking.istio.io/v1beta1
    selector:
      istio: ingressgateway
    servers:
      - port:
          number: 80
          name: http
          protocol: HTTP
        hosts:
          - "*" # "cluster1.multicluster.com"
