argocd-apps:
  applications: 

  - name: namespaces
    annotations:
      argocd.argoproj.io/sync-wave: "0"    
    namespace: argocd
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: argocd
    source:                 
      path: charts/apps/namespaces
      repoURL: https://github.com/canpolatoral/istio-multicluster-demo.git
      targetRevision: HEAD 
      helm:
        version: v3
        valueFiles:
        - values-cluster2.yaml 
    syncPolicy:
      automated:
        selfHeal: true
        prune: true 

  - name: gateways
    annotations:
      argocd.argoproj.io/sync-wave: "1"    
    namespace: argocd
    destination:
      namespace: istio-system
      server: https://kubernetes.default.svc
    project: argocd
    source:                 
      path: charts/apps/gateways
      repoURL: https://github.com/canpolatoral/istio-multicluster-demo.git
      targetRevision: HEAD 
      helm:
        version: v3
        valueFiles:
        - values-cluster2.yaml 
    syncPolicy:
      automated:
        selfHeal: true
        prune: true 


  - name: account-service
    annotations:
      argocd.argoproj.io/sync-wave: "2"    
    namespace: argocd
    destination:
      namespace: account
      server: https://kubernetes.default.svc
    project: argocd
    source:                 
      path: charts/apps/account
      repoURL: https://github.com/canpolatoral/istio-multicluster-demo.git
      targetRevision: HEAD 
      helm:
        version: v3
        valueFiles:
        - values-base.yaml
        - values-cluster2.yaml 
    syncPolicy:
      automated:
        selfHeal: true
        prune: true 

  - name: transfer-service
    annotations:
      argocd.argoproj.io/sync-wave: "2"    
    namespace: argocd
    destination:
      namespace: transfer
      server: https://kubernetes.default.svc
    project: argocd
    source:                 
      path: charts/apps/transfer
      repoURL: https://github.com/canpolatoral/istio-multicluster-demo.git
      targetRevision: HEAD 
      helm:
        version: v3
        valueFiles:
        - values-base.yaml
        - values-cluster2.yaml 
    syncPolicy:
      automated:
        selfHeal: true
        prune: true 

  - name: argocd-apps
    annotations:
      argocd.argoproj.io/sync-wave: "3"    
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:                 
      path: charts/argocd-apps
      repoURL: https://github.com/canpolatoral/istio-multicluster-demo.git
      targetRevision: HEAD 
      helm:
        version: v3
        valueFiles:
        - values-base.yaml
        - values-cluster2.yaml  
    syncPolicy:
      automated:
        selfHeal: true
        prune: true    