argocd-apps:
  applications: 
  - name: metrics-server
    annotations:
      argocd.argoproj.io/sync-wave: "0"    
    namespace: argocd
    destination:
      namespace: cert-manager
      server: https://kubernetes.default.svc
    project: kube-system
    source:                 
      path: charts/metrics-server
      repoURL: https://github.com/canpolatoral/istio-multicluster-demo.git
      targetRevision: HEAD 
      extraSourceFields: |
        helm:
          valueFiles:
          - values.yaml  
    syncPolicy:
      automated:
        selfHeal: true
        prune: true     

  - name: cert-manager
    annotations:
      argocd.argoproj.io/sync-wave: "1"    
    namespace: argocd
    destination:
      namespace: cert-manager
      server: https://kubernetes.default.svc
    project: argocd
    source:                 
      path: charts/cert-manager
      repoURL: https://github.com/canpolatoral/istio-multicluster-demo.git
      targetRevision: HEAD 
      extraSourceFields: |
        helm:
          valueFiles:
          - values-cluster2.yaml  
    syncPolicy:
      automated:
        selfHeal: true
        prune: true     

  - name: istio-csr
    annotations:
      argocd.argoproj.io/sync-wave: "2"    
    namespace: argocd
    destination:
      namespace: cert-manager
      server: https://kubernetes.default.svc
    project: argocd
    source:                 
      path: charts/cert-manager-istio-csr
      repoURL: https://github.com/canpolatoral/istio-multicluster-demo.git
      targetRevision: HEAD  
      extraSourceFields: |
        helm:
          valueFiles:
          - values-cluster2.yaml  
    syncPolicy:
      automated:
        selfHeal: true
        prune: true    

  - name: istio-base
    annotations:
      argocd.argoproj.io/sync-wave: "3"    
    namespace: argocd
    destination:
      namespace: istio-system
      server: https://kubernetes.default.svc
    project: argocd
    source:                 
      path: charts/istio/base
      repoURL: https://github.com/canpolatoral/istio-multicluster-demo.git
      targetRevision: HEAD  
      extraSourceFields: |
        helm:
          valueFiles:
          - values-cluster2.yaml  
    syncPolicy:
      automated:
        selfHeal: true
        prune: true      

  - name: istiod
    annotations:
      argocd.argoproj.io/sync-wave: "4"    
    namespace: argocd
    destination:
      namespace: istio-system
      server: https://kubernetes.default.svc
    project: argocd
    source:                 
      path: charts/istio/istiod
      repoURL: https://github.com/canpolatoral/istio-multicluster-demo.git
      targetRevision: HEAD 
      extraSourceFields: |
        helm:
          valueFiles:
          - values-cluster2.yaml    
    syncPolicy:
      automated:
        selfHeal: true
        prune: true     

  - name: istio-eastwestgateway
    annotations:
      argocd.argoproj.io/sync-wave: "5"    
    namespace: argocd
    destination:
      namespace: istio-system
      server: https://kubernetes.default.svc
    project: argocd
    source:                 
      path: charts/istio/gateway
      repoURL: https://github.com/canpolatoral/istio-multicluster-demo.git
      targetRevision: HEAD  
      extraSourceFields: |
        helm:
          valueFiles:
          - values-cluster2.yaml  
    syncPolicy:
      automated:
        selfHeal: true
        prune: true     