{{- if .Values.authorizationPolicy.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "ms.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ms.name" . }}
  action: ALLOW
  rules:
{{- range .Values.authorizationPolicy.allowedServiceAccounts }}
  - from:
    - source:
        principals: ["cluster.local/ns/{{ .namespace }}/sa/{{ .serviceAccount }}"]
    to:
    - operation:
{{- if .methods }}
        methods: {{ .methods | toYaml | nindent 8 }}
{{- end }}
{{- if .paths }}
        paths: {{ .paths | toYaml | nindent 8 }}
{{- end }}
{{- end }}
{{- range .Values.authorizationPolicy.allowedClients }}
  - from:
    - source:
        principals: ["{{ .issuer }}/{{ .clientId }}"]
    to:
{{- if .methods }}
        methods: {{ .methods | toYaml | nindent 8 }}
{{- end }}
{{- if .paths }}
        paths: {{ .paths | toYaml | nindent 8 }}
{{- end }}
{{- end }}
{{- end }}