{{- if .Values.peerAuthentication.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "ms.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.mtls.mode }}
{{- end }}