{{- if .Values.requestAuthentication.enabled }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ include "ms.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ms.name" . }}
  jwtRules:
{{- range .Values.requestAuthentication.jwtRules }}
  - issuer: "{{ .issuer }}"
{{- if .jwksUri }}
    jwksUri: "{{ .jwksUri }}"
{{- end }}
{{- if .jwks }}
    jwks: {{ .jwks }}
{{- end }}
{{- end }}
{{- end }}