# Default values for transfer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
base-ms-chart:

  nameOverride: "transfer-service"
  fullnameOverride: "transfer-service"

  image:
    repository: canpolatoral/transfer-service
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  mtls:
    mode: STRICT

  virtualService:
    enabled: true

    hosts:
      - "multicluster.mydemo.com"
    gateways:
      - "istio-system/ingress-gateway"
    http:
      match:
        prefix: "/transfer"
      rewrite:
        uri: "/"
      route:
        destination:
          host: "transfer-service.transfer.svc.cluster.local"
          port:
            number: 80