image:
  repository: canpolatoral/transfer-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

istio-injection: enabled

env:
  - name: PORT
    value: "80"
  - name: ACCOUNT_SERVICE_URL
    value: "http://account-service.account.svc"
  - name: VERSION
    value: "ABU DHABI"