image:
  repository: canpolatoral/account-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

istio-injection: enabled

env:
  - name: PORT
    value: "80"
  - name: VERSION
    value: "MEYDAN"