base-ms-chart:

  env:
    - name: PORT
      value: "80"
    - name: TARGET_SERVICE_URL
      value: "http://account-service.account.svc"
    - name: VERSION
      value: "ABU DHABI"
    - name: SERVICE_NAME
      value: "Customer Service"
    - name: CLIENT_CREDENTIALS_AUTH_ENABLED
      value: "true"
    - name: JWT_AUTH_URL
      value: "http://keycloak.keycloak.svc/realms/test/protocol/openid-connect/token"
    - name: CLIENT_ID
      value: "test-client-id"
    - name: CLIENT_SECRET
      value:  "test-secret"

  destinationRule:
    enabled: true

    trafficPolicy:
      connectionPool:
        http:
          maxRequestsPerConnection: 1

      loadBalancer:
        simple: ROUND_ROBIN
        localityLbSetting:
          enabled: true
          failover:
            - from: zone2
              to: zone1

      outlierDetection:
        consecutive5xxErrors: 1
        interval: "1s"
        baseEjectionTime: "1m"

  virtualService:
    enabled: true

    hosts:
      - "cluster2.multicluster.com"
    gateways:
      - "istio-ingress/ingress-gateway"
    http:
      match:
        prefix: "/customer"
      rewrite:
        uri: "/test"
      route:
        destination:
          host: "customer-service.customer.svc.cluster.local"
          port:
            number: 80