# Default values for transfer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
base-ms-chart:

  nameOverride: "customer-service"
  fullnameOverride: "customer-service"

  image:
    repository: canpolatoral/caller-service
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0.10"

  peerAuthentication:
    enabled: true
    
    mtls:
      mode: STRICT